/********************************************************************************
** Form generated from reading UI file 'Game.ui'
**
** Created by: Qt User Interface Compiler version 6.2.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GAME_H
#define UI_GAME_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Form
{
public:
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_12;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QLabel *label_62;
    QLabel *label_63;
    QLabel *label_64;
    QLabel *label_65;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *label_68;
    QLabel *label_69;
    QLabel *label_70;
    QLabel *label_71;
    QLabel *label_72;
    QLabel *label_73;
    QLabel *label_74;
    QLabel *label_75;
    QLabel *label_76;
    QLabel *label_77;
    QLabel *label_78;
    QLabel *label_79;
    QLabel *label_80;
    QLabel *label_81;
    QLabel *label_82;
    QLabel *label_83;
    QLabel *label_84;
    QLabel *label_85;
    QLabel *label_86;
    QLabel *label_87;
    QLabel *label_88;
    QLabel *label_89;
    QLabel *label_90;
    QLabel *label_91;
    QLabel *label_92;
    QLabel *label_93;
    QLabel *label_94;
    QLabel *label_95;
    QLabel *label_96;
    QLabel *label_97;
    QLabel *label_98;
    QLabel *label_99;
    QLabel *label_100;
    QLabel *label_101;
    QLabel *label_102;
    QLabel *label_103;
    QLabel *label_104;
    QLabel *label_105;
    QLabel *label_106;
    QLabel *label_107;
    QLabel *label_108;
    QLabel *label_109;
    QLabel *label_110;
    QLabel *label_111;
    QLabel *label_112;
    QLabel *label_113;
    QLabel *label_114;
    QLabel *label_115;
    QLabel *label_116;
    QLabel *label_117;
    QLabel *label_118;
    QLabel *label_119;
    QLabel *label_120;
    QLabel *label_121;
    QLabel *label_122;
    QLabel *label_123;
    QLabel *label_126;
    QLabel *label_127;
    QLabel *label_128;
    QLabel *label_129;
    QLabel *label_130;
    QLabel *label_131;
    QLabel *label_132;
    QLabel *label_133;
    QLabel *label_134;
    QLabel *label_135;
    QLabel *label_136;
    QLabel *label_137;
    QLabel *label_138;
    QLabel *label_139;
    QLabel *label_140;
    QLabel *label_141;
    QLabel *label_142;
    QLabel *label_143;
    QLabel *label_145;
    QLabel *label_146;
    QLabel *label_147;
    QLabel *label_148;
    QLabel *label_149;
    QLabel *label_151;
    QLabel *label_152;
    QLabel *label_153;
    QLabel *label_154;
    QLabel *label_155;
    QLabel *label_156;
    QLabel *label_157;
    QLabel *label_158;
    QLabel *label_159;
    QLabel *label_161;
    QLabel *label_162;
    QLabel *label_163;
    QLabel *label_164;
    QLabel *label_165;
    QLabel *label_166;
    QLabel *label_167;
    QLabel *label_168;
    QLabel *label_169;
    QLabel *label_170;
    QLabel *label_171;
    QLabel *label_172;
    QLabel *label_173;
    QLabel *label_174;
    QLabel *label_175;
    QLabel *label_176;
    QLabel *label_177;
    QLabel *label_179;
    QLabel *label_180;
    QLabel *label_182;
    QLabel *label_183;
    QLabel *label_186;
    QLabel *label_188;
    QLabel *label_189;
    QLabel *label_190;
    QLabel *label_191;
    QLabel *label_194;
    QLabel *label_195;
    QLabel *label_196;
    QLabel *label_197;
    QLabel *label_198;
    QLabel *label_199;
    QLabel *label_200;
    QLabel *label_201;
    QLabel *label_202;
    QLabel *label_203;
    QLabel *label_204;
    QLabel *label_205;
    QLabel *label_206;
    QLabel *label_207;
    QLabel *label_208;
    QLabel *label_209;
    QLabel *label_210;
    QLabel *label_211;
    QLabel *label_212;
    QLabel *label_213;
    QLabel *label_214;
    QLabel *label_215;
    QLabel *label_216;
    QLabel *label_217;
    QLabel *label_219;
    QLabel *label_220;
    QLabel *label_221;
    QLabel *label_222;
    QLabel *label_223;
    QLabel *label_224;
    QLabel *label_227;
    QLabel *label_228;
    QLabel *label_229;
    QLabel *label_230;
    QLabel *label_231;
    QLabel *label_232;
    QLabel *label_233;
    QLabel *label_234;
    QLabel *label_235;
    QLabel *label_236;
    QLabel *label_237;
    QLabel *label_238;
    QLabel *label_239;
    QLabel *label_240;
    QPushButton *pushButton;

    void setupUi(QWidget *Form)
    {
        if (Form->objectName().isEmpty())
            Form->setObjectName(QString::fromUtf8("Form"));
        Form->resize(1400, 1000);
        label = new QLabel(Form);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(0, 0, 60, 60));
        label_2 = new QLabel(Form);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(60, 0, 60, 60));
        label_3 = new QLabel(Form);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(180, 0, 60, 60));
        label_4 = new QLabel(Form);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(120, 0, 60, 60));
        label_5 = new QLabel(Form);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(300, 0, 60, 60));
        label_6 = new QLabel(Form);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(420, 0, 60, 60));
        label_7 = new QLabel(Form);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(240, 0, 60, 60));
        label_8 = new QLabel(Form);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(360, 0, 60, 60));
        label_9 = new QLabel(Form);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(780, 0, 60, 60));
        label_10 = new QLabel(Form);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(540, 0, 60, 60));
        label_11 = new QLabel(Form);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(660, 0, 60, 60));
        label_13 = new QLabel(Form);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(480, 0, 60, 60));
        label_14 = new QLabel(Form);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(720, 0, 60, 60));
        label_15 = new QLabel(Form);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(600, 0, 60, 60));
        label_16 = new QLabel(Form);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(840, 0, 60, 60));
        label_12 = new QLabel(Form);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(300, 60, 60, 60));
        label_17 = new QLabel(Form);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(600, 60, 60, 60));
        label_18 = new QLabel(Form);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(180, 60, 60, 60));
        label_19 = new QLabel(Form);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(420, 60, 60, 60));
        label_20 = new QLabel(Form);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(480, 60, 60, 60));
        label_21 = new QLabel(Form);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(60, 60, 60, 60));
        label_22 = new QLabel(Form);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(840, 60, 60, 60));
        label_23 = new QLabel(Form);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(0, 60, 60, 60));
        label_24 = new QLabel(Form);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(240, 60, 60, 60));
        label_25 = new QLabel(Form);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(720, 60, 60, 60));
        label_26 = new QLabel(Form);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(540, 60, 60, 60));
        label_27 = new QLabel(Form);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(120, 60, 60, 60));
        label_28 = new QLabel(Form);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(780, 60, 60, 60));
        label_29 = new QLabel(Form);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(660, 60, 60, 60));
        label_30 = new QLabel(Form);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(360, 60, 60, 60));
        label_31 = new QLabel(Form);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(300, 120, 60, 60));
        label_32 = new QLabel(Form);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(600, 120, 60, 60));
        label_33 = new QLabel(Form);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(480, 180, 60, 60));
        label_34 = new QLabel(Form);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(660, 180, 60, 60));
        label_35 = new QLabel(Form);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(420, 120, 60, 60));
        label_36 = new QLabel(Form);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(720, 180, 60, 60));
        label_37 = new QLabel(Form);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(420, 180, 60, 60));
        label_38 = new QLabel(Form);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(480, 120, 60, 60));
        label_39 = new QLabel(Form);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(840, 180, 60, 60));
        label_40 = new QLabel(Form);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(360, 180, 60, 60));
        label_41 = new QLabel(Form);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(0, 180, 60, 60));
        label_42 = new QLabel(Form);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(60, 120, 60, 60));
        label_43 = new QLabel(Form);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(600, 180, 60, 60));
        label_44 = new QLabel(Form);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(180, 180, 60, 60));
        label_45 = new QLabel(Form);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(120, 180, 60, 60));
        label_46 = new QLabel(Form);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(240, 120, 60, 60));
        label_47 = new QLabel(Form);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(720, 120, 60, 60));
        label_48 = new QLabel(Form);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(540, 120, 60, 60));
        label_49 = new QLabel(Form);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(360, 120, 60, 60));
        label_50 = new QLabel(Form);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(180, 120, 60, 60));
        label_51 = new QLabel(Form);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(300, 180, 60, 60));
        label_52 = new QLabel(Form);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(840, 120, 60, 60));
        label_53 = new QLabel(Form);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(60, 180, 60, 60));
        label_54 = new QLabel(Form);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(0, 120, 60, 60));
        label_55 = new QLabel(Form);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(540, 180, 60, 60));
        label_56 = new QLabel(Form);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(240, 180, 60, 60));
        label_57 = new QLabel(Form);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(120, 120, 60, 60));
        label_58 = new QLabel(Form);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(780, 120, 60, 60));
        label_59 = new QLabel(Form);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(660, 120, 60, 60));
        label_60 = new QLabel(Form);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(780, 180, 60, 60));
        label_61 = new QLabel(Form);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(300, 240, 60, 60));
        label_62 = new QLabel(Form);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(600, 240, 60, 60));
        label_63 = new QLabel(Form);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(660, 300, 60, 60));
        label_64 = new QLabel(Form);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(360, 360, 60, 60));
        label_65 = new QLabel(Form);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(300, 420, 60, 60));
        label_66 = new QLabel(Form);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(600, 420, 60, 60));
        label_67 = new QLabel(Form);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(60, 420, 60, 60));
        label_68 = new QLabel(Form);
        label_68->setObjectName(QString::fromUtf8("label_68"));
        label_68->setGeometry(QRect(420, 300, 60, 60));
        label_69 = new QLabel(Form);
        label_69->setObjectName(QString::fromUtf8("label_69"));
        label_69->setGeometry(QRect(0, 360, 60, 60));
        label_70 = new QLabel(Form);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(840, 300, 60, 60));
        label_71 = new QLabel(Form);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(300, 360, 60, 60));
        label_72 = new QLabel(Form);
        label_72->setObjectName(QString::fromUtf8("label_72"));
        label_72->setGeometry(QRect(0, 300, 60, 60));
        label_73 = new QLabel(Form);
        label_73->setObjectName(QString::fromUtf8("label_73"));
        label_73->setGeometry(QRect(600, 300, 60, 60));
        label_74 = new QLabel(Form);
        label_74->setObjectName(QString::fromUtf8("label_74"));
        label_74->setGeometry(QRect(360, 420, 60, 60));
        label_75 = new QLabel(Form);
        label_75->setObjectName(QString::fromUtf8("label_75"));
        label_75->setGeometry(QRect(240, 240, 60, 60));
        label_76 = new QLabel(Form);
        label_76->setObjectName(QString::fromUtf8("label_76"));
        label_76->setGeometry(QRect(180, 360, 60, 60));
        label_77 = new QLabel(Form);
        label_77->setObjectName(QString::fromUtf8("label_77"));
        label_77->setGeometry(QRect(840, 360, 60, 60));
        label_78 = new QLabel(Form);
        label_78->setObjectName(QString::fromUtf8("label_78"));
        label_78->setGeometry(QRect(180, 240, 60, 60));
        label_79 = new QLabel(Form);
        label_79->setObjectName(QString::fromUtf8("label_79"));
        label_79->setGeometry(QRect(120, 420, 60, 60));
        label_80 = new QLabel(Form);
        label_80->setObjectName(QString::fromUtf8("label_80"));
        label_80->setGeometry(QRect(120, 360, 60, 60));
        label_81 = new QLabel(Form);
        label_81->setObjectName(QString::fromUtf8("label_81"));
        label_81->setGeometry(QRect(60, 300, 60, 60));
        label_82 = new QLabel(Form);
        label_82->setObjectName(QString::fromUtf8("label_82"));
        label_82->setGeometry(QRect(480, 420, 60, 60));
        label_83 = new QLabel(Form);
        label_83->setObjectName(QString::fromUtf8("label_83"));
        label_83->setGeometry(QRect(420, 420, 60, 60));
        label_84 = new QLabel(Form);
        label_84->setObjectName(QString::fromUtf8("label_84"));
        label_84->setGeometry(QRect(780, 420, 60, 60));
        label_85 = new QLabel(Form);
        label_85->setObjectName(QString::fromUtf8("label_85"));
        label_85->setGeometry(QRect(540, 300, 60, 60));
        label_86 = new QLabel(Form);
        label_86->setObjectName(QString::fromUtf8("label_86"));
        label_86->setGeometry(QRect(240, 300, 60, 60));
        label_87 = new QLabel(Form);
        label_87->setObjectName(QString::fromUtf8("label_87"));
        label_87->setGeometry(QRect(120, 240, 60, 60));
        label_88 = new QLabel(Form);
        label_88->setObjectName(QString::fromUtf8("label_88"));
        label_88->setGeometry(QRect(780, 300, 60, 60));
        label_89 = new QLabel(Form);
        label_89->setObjectName(QString::fromUtf8("label_89"));
        label_89->setGeometry(QRect(240, 420, 60, 60));
        label_90 = new QLabel(Form);
        label_90->setObjectName(QString::fromUtf8("label_90"));
        label_90->setGeometry(QRect(480, 300, 60, 60));
        label_91 = new QLabel(Form);
        label_91->setObjectName(QString::fromUtf8("label_91"));
        label_91->setGeometry(QRect(420, 240, 60, 60));
        label_92 = new QLabel(Form);
        label_92->setObjectName(QString::fromUtf8("label_92"));
        label_92->setGeometry(QRect(720, 300, 60, 60));
        label_93 = new QLabel(Form);
        label_93->setObjectName(QString::fromUtf8("label_93"));
        label_93->setGeometry(QRect(60, 360, 60, 60));
        label_94 = new QLabel(Form);
        label_94->setObjectName(QString::fromUtf8("label_94"));
        label_94->setGeometry(QRect(480, 240, 60, 60));
        label_95 = new QLabel(Form);
        label_95->setObjectName(QString::fromUtf8("label_95"));
        label_95->setGeometry(QRect(780, 360, 60, 60));
        label_96 = new QLabel(Form);
        label_96->setObjectName(QString::fromUtf8("label_96"));
        label_96->setGeometry(QRect(360, 300, 60, 60));
        label_97 = new QLabel(Form);
        label_97->setObjectName(QString::fromUtf8("label_97"));
        label_97->setGeometry(QRect(540, 420, 60, 60));
        label_98 = new QLabel(Form);
        label_98->setObjectName(QString::fromUtf8("label_98"));
        label_98->setGeometry(QRect(600, 360, 60, 60));
        label_99 = new QLabel(Form);
        label_99->setObjectName(QString::fromUtf8("label_99"));
        label_99->setGeometry(QRect(60, 240, 60, 60));
        label_100 = new QLabel(Form);
        label_100->setObjectName(QString::fromUtf8("label_100"));
        label_100->setGeometry(QRect(180, 300, 60, 60));
        label_101 = new QLabel(Form);
        label_101->setObjectName(QString::fromUtf8("label_101"));
        label_101->setGeometry(QRect(120, 300, 60, 60));
        label_102 = new QLabel(Form);
        label_102->setObjectName(QString::fromUtf8("label_102"));
        label_102->setGeometry(QRect(660, 420, 60, 60));
        label_103 = new QLabel(Form);
        label_103->setObjectName(QString::fromUtf8("label_103"));
        label_103->setGeometry(QRect(720, 240, 60, 60));
        label_104 = new QLabel(Form);
        label_104->setObjectName(QString::fromUtf8("label_104"));
        label_104->setGeometry(QRect(480, 360, 60, 60));
        label_105 = new QLabel(Form);
        label_105->setObjectName(QString::fromUtf8("label_105"));
        label_105->setGeometry(QRect(540, 240, 60, 60));
        label_106 = new QLabel(Form);
        label_106->setObjectName(QString::fromUtf8("label_106"));
        label_106->setGeometry(QRect(420, 360, 60, 60));
        label_107 = new QLabel(Form);
        label_107->setObjectName(QString::fromUtf8("label_107"));
        label_107->setGeometry(QRect(180, 420, 60, 60));
        label_108 = new QLabel(Form);
        label_108->setObjectName(QString::fromUtf8("label_108"));
        label_108->setGeometry(QRect(360, 240, 60, 60));
        label_109 = new QLabel(Form);
        label_109->setObjectName(QString::fromUtf8("label_109"));
        label_109->setGeometry(QRect(240, 360, 60, 60));
        label_110 = new QLabel(Form);
        label_110->setObjectName(QString::fromUtf8("label_110"));
        label_110->setGeometry(QRect(720, 360, 60, 60));
        label_111 = new QLabel(Form);
        label_111->setObjectName(QString::fromUtf8("label_111"));
        label_111->setGeometry(QRect(300, 300, 60, 60));
        label_112 = new QLabel(Form);
        label_112->setObjectName(QString::fromUtf8("label_112"));
        label_112->setGeometry(QRect(720, 420, 60, 60));
        label_113 = new QLabel(Form);
        label_113->setObjectName(QString::fromUtf8("label_113"));
        label_113->setGeometry(QRect(840, 240, 60, 60));
        label_114 = new QLabel(Form);
        label_114->setObjectName(QString::fromUtf8("label_114"));
        label_114->setGeometry(QRect(0, 240, 60, 60));
        label_115 = new QLabel(Form);
        label_115->setObjectName(QString::fromUtf8("label_115"));
        label_115->setGeometry(QRect(0, 420, 60, 60));
        label_116 = new QLabel(Form);
        label_116->setObjectName(QString::fromUtf8("label_116"));
        label_116->setGeometry(QRect(660, 360, 60, 60));
        label_117 = new QLabel(Form);
        label_117->setObjectName(QString::fromUtf8("label_117"));
        label_117->setGeometry(QRect(780, 240, 60, 60));
        label_118 = new QLabel(Form);
        label_118->setObjectName(QString::fromUtf8("label_118"));
        label_118->setGeometry(QRect(660, 240, 60, 60));
        label_119 = new QLabel(Form);
        label_119->setObjectName(QString::fromUtf8("label_119"));
        label_119->setGeometry(QRect(840, 420, 60, 60));
        label_120 = new QLabel(Form);
        label_120->setObjectName(QString::fromUtf8("label_120"));
        label_120->setGeometry(QRect(540, 360, 60, 60));
        label_121 = new QLabel(Form);
        label_121->setObjectName(QString::fromUtf8("label_121"));
        label_121->setGeometry(QRect(840, 660, 60, 60));
        label_122 = new QLabel(Form);
        label_122->setObjectName(QString::fromUtf8("label_122"));
        label_122->setGeometry(QRect(600, 480, 60, 60));
        label_123 = new QLabel(Form);
        label_123->setObjectName(QString::fromUtf8("label_123"));
        label_123->setGeometry(QRect(660, 540, 60, 60));
        label_126 = new QLabel(Form);
        label_126->setObjectName(QString::fromUtf8("label_126"));
        label_126->setGeometry(QRect(600, 660, 60, 60));
        label_127 = new QLabel(Form);
        label_127->setObjectName(QString::fromUtf8("label_127"));
        label_127->setGeometry(QRect(420, 540, 60, 60));
        label_128 = new QLabel(Form);
        label_128->setObjectName(QString::fromUtf8("label_128"));
        label_128->setGeometry(QRect(0, 600, 60, 60));
        label_129 = new QLabel(Form);
        label_129->setObjectName(QString::fromUtf8("label_129"));
        label_129->setGeometry(QRect(300, 600, 60, 60));
        label_130 = new QLabel(Form);
        label_130->setObjectName(QString::fromUtf8("label_130"));
        label_130->setGeometry(QRect(720, 840, 60, 60));
        label_131 = new QLabel(Form);
        label_131->setObjectName(QString::fromUtf8("label_131"));
        label_131->setGeometry(QRect(840, 780, 60, 60));
        label_132 = new QLabel(Form);
        label_132->setObjectName(QString::fromUtf8("label_132"));
        label_132->setGeometry(QRect(60, 720, 60, 60));
        label_133 = new QLabel(Form);
        label_133->setObjectName(QString::fromUtf8("label_133"));
        label_133->setGeometry(QRect(360, 840, 60, 60));
        label_134 = new QLabel(Form);
        label_134->setObjectName(QString::fromUtf8("label_134"));
        label_134->setGeometry(QRect(360, 660, 60, 60));
        label_135 = new QLabel(Form);
        label_135->setObjectName(QString::fromUtf8("label_135"));
        label_135->setGeometry(QRect(600, 720, 60, 60));
        label_136 = new QLabel(Form);
        label_136->setObjectName(QString::fromUtf8("label_136"));
        label_136->setGeometry(QRect(240, 480, 60, 60));
        label_137 = new QLabel(Form);
        label_137->setObjectName(QString::fromUtf8("label_137"));
        label_137->setGeometry(QRect(240, 840, 60, 60));
        label_138 = new QLabel(Form);
        label_138->setObjectName(QString::fromUtf8("label_138"));
        label_138->setGeometry(QRect(180, 600, 60, 60));
        label_139 = new QLabel(Form);
        label_139->setObjectName(QString::fromUtf8("label_139"));
        label_139->setGeometry(QRect(120, 660, 60, 60));
        label_140 = new QLabel(Form);
        label_140->setObjectName(QString::fromUtf8("label_140"));
        label_140->setGeometry(QRect(420, 840, 60, 60));
        label_141 = new QLabel(Form);
        label_141->setObjectName(QString::fromUtf8("label_141"));
        label_141->setGeometry(QRect(420, 780, 60, 60));
        label_142 = new QLabel(Form);
        label_142->setObjectName(QString::fromUtf8("label_142"));
        label_142->setGeometry(QRect(180, 780, 60, 60));
        label_143 = new QLabel(Form);
        label_143->setObjectName(QString::fromUtf8("label_143"));
        label_143->setGeometry(QRect(240, 720, 60, 60));
        label_145 = new QLabel(Form);
        label_145->setObjectName(QString::fromUtf8("label_145"));
        label_145->setGeometry(QRect(480, 660, 60, 60));
        label_146 = new QLabel(Form);
        label_146->setObjectName(QString::fromUtf8("label_146"));
        label_146->setGeometry(QRect(540, 540, 60, 60));
        label_147 = new QLabel(Form);
        label_147->setObjectName(QString::fromUtf8("label_147"));
        label_147->setGeometry(QRect(780, 840, 60, 60));
        label_148 = new QLabel(Form);
        label_148->setObjectName(QString::fromUtf8("label_148"));
        label_148->setGeometry(QRect(180, 840, 60, 60));
        label_149 = new QLabel(Form);
        label_149->setObjectName(QString::fromUtf8("label_149"));
        label_149->setGeometry(QRect(240, 660, 60, 60));
        label_151 = new QLabel(Form);
        label_151->setObjectName(QString::fromUtf8("label_151"));
        label_151->setGeometry(QRect(480, 540, 60, 60));
        label_152 = new QLabel(Form);
        label_152->setObjectName(QString::fromUtf8("label_152"));
        label_152->setGeometry(QRect(60, 600, 60, 60));
        label_153 = new QLabel(Form);
        label_153->setObjectName(QString::fromUtf8("label_153"));
        label_153->setGeometry(QRect(360, 540, 60, 60));
        label_154 = new QLabel(Form);
        label_154->setObjectName(QString::fromUtf8("label_154"));
        label_154->setGeometry(QRect(600, 600, 60, 60));
        label_155 = new QLabel(Form);
        label_155->setObjectName(QString::fromUtf8("label_155"));
        label_155->setGeometry(QRect(180, 540, 60, 60));
        label_156 = new QLabel(Form);
        label_156->setObjectName(QString::fromUtf8("label_156"));
        label_156->setGeometry(QRect(660, 660, 60, 60));
        label_157 = new QLabel(Form);
        label_157->setObjectName(QString::fromUtf8("label_157"));
        label_157->setGeometry(QRect(720, 780, 60, 60));
        label_158 = new QLabel(Form);
        label_158->setObjectName(QString::fromUtf8("label_158"));
        label_158->setGeometry(QRect(780, 720, 60, 60));
        label_159 = new QLabel(Form);
        label_159->setObjectName(QString::fromUtf8("label_159"));
        label_159->setGeometry(QRect(120, 720, 60, 60));
        label_161 = new QLabel(Form);
        label_161->setObjectName(QString::fromUtf8("label_161"));
        label_161->setGeometry(QRect(300, 780, 60, 60));
        label_162 = new QLabel(Form);
        label_162->setObjectName(QString::fromUtf8("label_162"));
        label_162->setGeometry(QRect(420, 600, 60, 60));
        label_163 = new QLabel(Form);
        label_163->setObjectName(QString::fromUtf8("label_163"));
        label_163->setGeometry(QRect(360, 480, 60, 60));
        label_164 = new QLabel(Form);
        label_164->setObjectName(QString::fromUtf8("label_164"));
        label_164->setGeometry(QRect(420, 720, 60, 60));
        label_165 = new QLabel(Form);
        label_165->setObjectName(QString::fromUtf8("label_165"));
        label_165->setGeometry(QRect(720, 600, 60, 60));
        label_166 = new QLabel(Form);
        label_166->setObjectName(QString::fromUtf8("label_166"));
        label_166->setGeometry(QRect(840, 840, 60, 60));
        label_167 = new QLabel(Form);
        label_167->setObjectName(QString::fromUtf8("label_167"));
        label_167->setGeometry(QRect(720, 720, 60, 60));
        label_168 = new QLabel(Form);
        label_168->setObjectName(QString::fromUtf8("label_168"));
        label_168->setGeometry(QRect(600, 780, 60, 60));
        label_169 = new QLabel(Form);
        label_169->setObjectName(QString::fromUtf8("label_169"));
        label_169->setGeometry(QRect(180, 720, 60, 60));
        label_170 = new QLabel(Form);
        label_170->setObjectName(QString::fromUtf8("label_170"));
        label_170->setGeometry(QRect(840, 480, 60, 60));
        label_171 = new QLabel(Form);
        label_171->setObjectName(QString::fromUtf8("label_171"));
        label_171->setGeometry(QRect(0, 660, 60, 60));
        label_172 = new QLabel(Form);
        label_172->setObjectName(QString::fromUtf8("label_172"));
        label_172->setGeometry(QRect(660, 600, 60, 60));
        label_173 = new QLabel(Form);
        label_173->setObjectName(QString::fromUtf8("label_173"));
        label_173->setGeometry(QRect(360, 720, 60, 60));
        label_174 = new QLabel(Form);
        label_174->setObjectName(QString::fromUtf8("label_174"));
        label_174->setGeometry(QRect(540, 600, 60, 60));
        label_175 = new QLabel(Form);
        label_175->setObjectName(QString::fromUtf8("label_175"));
        label_175->setGeometry(QRect(300, 480, 60, 60));
        label_176 = new QLabel(Form);
        label_176->setObjectName(QString::fromUtf8("label_176"));
        label_176->setGeometry(QRect(360, 600, 60, 60));
        label_177 = new QLabel(Form);
        label_177->setObjectName(QString::fromUtf8("label_177"));
        label_177->setGeometry(QRect(660, 720, 60, 60));
        label_179 = new QLabel(Form);
        label_179->setObjectName(QString::fromUtf8("label_179"));
        label_179->setGeometry(QRect(840, 540, 60, 60));
        label_180 = new QLabel(Form);
        label_180->setObjectName(QString::fromUtf8("label_180"));
        label_180->setGeometry(QRect(0, 540, 60, 60));
        label_182 = new QLabel(Form);
        label_182->setObjectName(QString::fromUtf8("label_182"));
        label_182->setGeometry(QRect(600, 540, 60, 60));
        label_183 = new QLabel(Form);
        label_183->setObjectName(QString::fromUtf8("label_183"));
        label_183->setGeometry(QRect(60, 780, 60, 60));
        label_186 = new QLabel(Form);
        label_186->setObjectName(QString::fromUtf8("label_186"));
        label_186->setGeometry(QRect(840, 600, 60, 60));
        label_188 = new QLabel(Form);
        label_188->setObjectName(QString::fromUtf8("label_188"));
        label_188->setGeometry(QRect(180, 480, 60, 60));
        label_189 = new QLabel(Form);
        label_189->setObjectName(QString::fromUtf8("label_189"));
        label_189->setGeometry(QRect(360, 780, 60, 60));
        label_190 = new QLabel(Form);
        label_190->setObjectName(QString::fromUtf8("label_190"));
        label_190->setGeometry(QRect(300, 720, 60, 60));
        label_191 = new QLabel(Form);
        label_191->setObjectName(QString::fromUtf8("label_191"));
        label_191->setGeometry(QRect(120, 600, 60, 60));
        label_194 = new QLabel(Form);
        label_194->setObjectName(QString::fromUtf8("label_194"));
        label_194->setGeometry(QRect(60, 540, 60, 60));
        label_195 = new QLabel(Form);
        label_195->setObjectName(QString::fromUtf8("label_195"));
        label_195->setGeometry(QRect(300, 840, 60, 60));
        label_196 = new QLabel(Form);
        label_196->setObjectName(QString::fromUtf8("label_196"));
        label_196->setGeometry(QRect(420, 660, 60, 60));
        label_197 = new QLabel(Form);
        label_197->setObjectName(QString::fromUtf8("label_197"));
        label_197->setGeometry(QRect(780, 660, 60, 60));
        label_198 = new QLabel(Form);
        label_198->setObjectName(QString::fromUtf8("label_198"));
        label_198->setGeometry(QRect(780, 780, 60, 60));
        label_199 = new QLabel(Form);
        label_199->setObjectName(QString::fromUtf8("label_199"));
        label_199->setGeometry(QRect(240, 540, 60, 60));
        label_200 = new QLabel(Form);
        label_200->setObjectName(QString::fromUtf8("label_200"));
        label_200->setGeometry(QRect(0, 780, 60, 60));
        label_201 = new QLabel(Form);
        label_201->setObjectName(QString::fromUtf8("label_201"));
        label_201->setGeometry(QRect(120, 480, 60, 60));
        label_202 = new QLabel(Form);
        label_202->setObjectName(QString::fromUtf8("label_202"));
        label_202->setGeometry(QRect(780, 540, 60, 60));
        label_203 = new QLabel(Form);
        label_203->setObjectName(QString::fromUtf8("label_203"));
        label_203->setGeometry(QRect(480, 780, 60, 60));
        label_204 = new QLabel(Form);
        label_204->setObjectName(QString::fromUtf8("label_204"));
        label_204->setGeometry(QRect(480, 840, 60, 60));
        label_205 = new QLabel(Form);
        label_205->setObjectName(QString::fromUtf8("label_205"));
        label_205->setGeometry(QRect(540, 780, 60, 60));
        label_206 = new QLabel(Form);
        label_206->setObjectName(QString::fromUtf8("label_206"));
        label_206->setGeometry(QRect(240, 780, 60, 60));
        label_207 = new QLabel(Form);
        label_207->setObjectName(QString::fromUtf8("label_207"));
        label_207->setGeometry(QRect(420, 480, 60, 60));
        label_208 = new QLabel(Form);
        label_208->setObjectName(QString::fromUtf8("label_208"));
        label_208->setGeometry(QRect(720, 540, 60, 60));
        label_209 = new QLabel(Form);
        label_209->setObjectName(QString::fromUtf8("label_209"));
        label_209->setGeometry(QRect(60, 840, 60, 60));
        label_210 = new QLabel(Form);
        label_210->setObjectName(QString::fromUtf8("label_210"));
        label_210->setGeometry(QRect(480, 480, 60, 60));
        label_211 = new QLabel(Form);
        label_211->setObjectName(QString::fromUtf8("label_211"));
        label_211->setGeometry(QRect(780, 600, 60, 60));
        label_212 = new QLabel(Form);
        label_212->setObjectName(QString::fromUtf8("label_212"));
        label_212->setGeometry(QRect(540, 660, 60, 60));
        label_213 = new QLabel(Form);
        label_213->setObjectName(QString::fromUtf8("label_213"));
        label_213->setGeometry(QRect(120, 780, 60, 60));
        label_214 = new QLabel(Form);
        label_214->setObjectName(QString::fromUtf8("label_214"));
        label_214->setGeometry(QRect(0, 720, 60, 60));
        label_215 = new QLabel(Form);
        label_215->setObjectName(QString::fromUtf8("label_215"));
        label_215->setGeometry(QRect(540, 840, 60, 60));
        label_216 = new QLabel(Form);
        label_216->setObjectName(QString::fromUtf8("label_216"));
        label_216->setGeometry(QRect(540, 720, 60, 60));
        label_217 = new QLabel(Form);
        label_217->setObjectName(QString::fromUtf8("label_217"));
        label_217->setGeometry(QRect(60, 480, 60, 60));
        label_219 = new QLabel(Form);
        label_219->setObjectName(QString::fromUtf8("label_219"));
        label_219->setGeometry(QRect(120, 540, 60, 60));
        label_220 = new QLabel(Form);
        label_220->setObjectName(QString::fromUtf8("label_220"));
        label_220->setGeometry(QRect(480, 720, 60, 60));
        label_221 = new QLabel(Form);
        label_221->setObjectName(QString::fromUtf8("label_221"));
        label_221->setGeometry(QRect(720, 480, 60, 60));
        label_222 = new QLabel(Form);
        label_222->setObjectName(QString::fromUtf8("label_222"));
        label_222->setGeometry(QRect(480, 600, 60, 60));
        label_223 = new QLabel(Form);
        label_223->setObjectName(QString::fromUtf8("label_223"));
        label_223->setGeometry(QRect(540, 480, 60, 60));
        label_224 = new QLabel(Form);
        label_224->setObjectName(QString::fromUtf8("label_224"));
        label_224->setGeometry(QRect(180, 660, 60, 60));
        label_227 = new QLabel(Form);
        label_227->setObjectName(QString::fromUtf8("label_227"));
        label_227->setGeometry(QRect(660, 840, 60, 60));
        label_228 = new QLabel(Form);
        label_228->setObjectName(QString::fromUtf8("label_228"));
        label_228->setGeometry(QRect(240, 600, 60, 60));
        label_229 = new QLabel(Form);
        label_229->setObjectName(QString::fromUtf8("label_229"));
        label_229->setGeometry(QRect(0, 840, 60, 60));
        label_230 = new QLabel(Form);
        label_230->setObjectName(QString::fromUtf8("label_230"));
        label_230->setGeometry(QRect(120, 840, 60, 60));
        label_231 = new QLabel(Form);
        label_231->setObjectName(QString::fromUtf8("label_231"));
        label_231->setGeometry(QRect(840, 720, 60, 60));
        label_232 = new QLabel(Form);
        label_232->setObjectName(QString::fromUtf8("label_232"));
        label_232->setGeometry(QRect(300, 540, 60, 60));
        label_233 = new QLabel(Form);
        label_233->setObjectName(QString::fromUtf8("label_233"));
        label_233->setGeometry(QRect(720, 660, 60, 60));
        label_234 = new QLabel(Form);
        label_234->setObjectName(QString::fromUtf8("label_234"));
        label_234->setGeometry(QRect(0, 480, 60, 60));
        label_235 = new QLabel(Form);
        label_235->setObjectName(QString::fromUtf8("label_235"));
        label_235->setGeometry(QRect(600, 840, 60, 60));
        label_236 = new QLabel(Form);
        label_236->setObjectName(QString::fromUtf8("label_236"));
        label_236->setGeometry(QRect(660, 780, 60, 60));
        label_237 = new QLabel(Form);
        label_237->setObjectName(QString::fromUtf8("label_237"));
        label_237->setGeometry(QRect(780, 480, 60, 60));
        label_238 = new QLabel(Form);
        label_238->setObjectName(QString::fromUtf8("label_238"));
        label_238->setGeometry(QRect(660, 480, 60, 60));
        label_239 = new QLabel(Form);
        label_239->setObjectName(QString::fromUtf8("label_239"));
        label_239->setGeometry(QRect(300, 660, 60, 60));
        label_240 = new QLabel(Form);
        label_240->setObjectName(QString::fromUtf8("label_240"));
        label_240->setGeometry(QRect(60, 660, 60, 60));
        pushButton = new QPushButton(Form);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(1060, 40, 75, 24));

        retranslateUi(Form);

        QMetaObject::connectSlotsByName(Form);
    } // setupUi

    void retranslateUi(QWidget *Form)
    {
        Form->setWindowTitle(QCoreApplication::translate("Form", "Form", nullptr));
        label->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_2->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_3->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_4->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_5->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_6->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_7->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_8->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_9->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_10->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_11->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_13->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_14->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_15->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_16->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_12->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_17->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_18->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_19->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_20->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_21->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_22->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_23->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_24->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_25->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_26->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_27->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_28->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_29->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_30->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_31->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_32->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_33->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_34->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_35->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_36->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_37->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_38->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_39->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_40->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_41->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_42->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_43->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_44->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_45->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_46->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_47->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_48->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_49->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_50->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_51->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_52->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_53->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_54->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_55->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_56->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_57->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_58->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_59->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_60->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_61->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_62->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_63->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_64->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_65->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_66->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_67->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_68->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_69->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_70->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_71->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_72->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_73->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_74->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_75->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_76->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_77->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_78->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_79->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_80->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_81->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_82->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_83->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_84->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_85->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_86->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_87->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_88->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_89->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_90->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_91->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_92->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_93->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_94->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_95->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_96->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_97->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_98->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_99->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_100->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_101->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_102->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_103->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_104->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_105->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_106->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_107->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_108->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_109->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_110->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_111->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_112->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_113->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_114->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_115->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_116->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_117->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_118->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_119->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_120->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_121->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_122->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_123->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_126->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_127->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_128->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_129->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_130->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_131->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_132->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_133->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_134->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_135->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_136->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_137->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_138->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_139->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_140->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_141->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_142->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_143->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_145->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_146->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_147->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_148->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_149->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_151->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_152->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_153->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_154->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_155->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_156->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_157->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_158->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_159->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_161->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_162->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_163->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_164->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_165->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_166->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_167->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_168->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_169->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_170->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_171->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_172->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_173->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_174->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_175->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_176->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_177->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_179->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_180->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_182->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_183->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_186->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_188->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_189->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_190->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_191->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_194->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_195->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_196->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_197->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_198->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_199->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_200->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_201->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_202->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_203->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_204->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_205->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_206->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_207->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_208->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_209->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_210->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_211->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_212->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_213->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_214->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_215->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_216->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_217->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_219->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_220->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_221->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_222->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_223->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_224->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_227->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_228->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_229->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_230->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_231->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_232->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_233->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_234->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_235->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_236->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_237->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_238->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_239->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        label_240->setText(QCoreApplication::translate("Form", "TextLabel", nullptr));
        pushButton->setText(QCoreApplication::translate("Form", "Powrot", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Form: public Ui_Form {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GAME_H
